version: "3.3"
services:
  web:
    hostname: web
    container_name: web
    build:
      context: ..
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
      #      - ../../../volumes/web/logs:/var/log/nginx
      - ./nginx/conf/site.conf:/etc/nginx/conf.d/site.conf
  php:
    hostname: php
    container_name: php
    build:
      context: ..
      dockerfile: ./docker/php/Dockerfile
    restart: always
    volumes:
      - ../src:/var/www/html
      - ./php/conf/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php/conf/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
  db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  memcached:
    image: 'bitnami/memcached:latest'
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379"